class_name SiteRuntimeFailureReason
extends RefCounted

enum Code {
	NONE,
	INVALID_SITE_ID,
	SITE_NOT_FOUND,
	SITE_IDENTITY_MISMATCH,
	INVALID_FEATURE_ID,
	DUPLICATE_FEATURE,
	FEATURE_NOT_FOUND,
	INVALID_PARTY,
	PARTY_NOT_AT_SITE,
	INVALID_DIRECTION,
	OUT_OF_BOUNDS,
	BLOCKED,
	INVALID_FACILITY_TYPE,
	INVALID_FOOTPRINT,
}

static func to_code(reason: int) -> String:
	match reason:
		Code.INVALID_SITE_ID:
			return "INVALID_SITE_ID"
		Code.SITE_NOT_FOUND:
			return "SITE_NOT_FOUND"
		Code.SITE_IDENTITY_MISMATCH:
			return "SITE_IDENTITY_MISMATCH"
		Code.INVALID_FEATURE_ID:
			return "INVALID_FEATURE_ID"
		Code.DUPLICATE_FEATURE:
			return "DUPLICATE_FEATURE"
		Code.FEATURE_NOT_FOUND:
			return "FEATURE_NOT_FOUND"
		Code.INVALID_PARTY:
			return "INVALID_PARTY"
		Code.PARTY_NOT_AT_SITE:
			return "PARTY_NOT_AT_SITE"
		Code.INVALID_DIRECTION:
			return "INVALID_DIRECTION"
		Code.OUT_OF_BOUNDS:
			return "OUT_OF_BOUNDS"
		Code.BLOCKED:
			return "BLOCKED"
		Code.INVALID_FACILITY_TYPE:
			return "INVALID_FACILITY_TYPE"
		Code.INVALID_FOOTPRINT:
			return "INVALID_FOOTPRINT"
		_:
			return "NONE"
