extends SceneTree

var geometry_calls := 0

func _initialize() -> void:
	call_deferred("run")

func _weapon(data: TerrainData, row: Dictionary, asset: String) -> String:
	var made := SiteRuntime.create_equipment(data, row.item_state, "ranged_test_" + asset,
		{"slot": "weapon", "asset": asset, "tint": [1.0, 1.0, 1.0, 1.0]}, int(row.person_id))
	assert(made.ok)
	return str(made.item_id)

func _packet(kind: String, hp: float, stun: float, stagger: float) -> Dictionary:
	return {"shield": false, "result": {"kind": kind, "hp": hp, "stun": stun, "stagger": stagger, "knockback": false}}

func run() -> void:
	create_timer(18.0).timeout.connect(func() -> void: quit(1))
	var data := TerrainData.new()
	data.allocate(Vector2i(40, 40))
	data.flags.fill(TerrainData.Flag.WALKABLE)
	SiteEnvironment.initialize(data, "ranged-army-owner")
	data.static_blocked.fill(0)
	assert(SiteRuntime.initialize_item_storage(data.site).ok)
	var army := TerrainArmy.new()
	root.add_child(army)
	army.set_process(false)
	army.exchange_enabled = true
	army.roster_size = 3
	var selected: Array[Vector2i] = [Vector2i(10, 10), Vector2i(12, 10), Vector2i(13, 10)]
	assert(army.deploy_at(data, null, null, selected) and army.enable_combat(false))
	for initial_row: Dictionary in army.combat_units:
		initial_row.cargo = {"arrow": 0, "bolt": 2}
		initial_row.appearance = TerrainArmy._combat_bake.manifest.appearance.duplicate(true)
		initial_row.appearance.parts.shield = "none"
		initial_row.item_state = {}
		assert(HumanCharacter3DEditor.valid_appearance(initial_row.appearance), "Fixture starts with a valid published body recipe")
		assert(SiteRuntime.seed_person_equipment(data, initial_row.item_state, int(initial_row.person_id), initial_row.appearance).ok,
			"Fixture registers the original full equipment through its canonical item owner")
	army.equipment_appearance_query = func(identity: int) -> Dictionary:
		var index := army.index_for_identity(identity)
		assert(index >= 0, "Fixture appearance query resolves the original row identity")
		var original_row: Dictionary = army.combat_units[index]
		assert(SiteRuntime._item_holder_shape(original_row.item_state), "Fixture holder retains actual equipment identities")
		var appearance := SiteRuntime.equipment_appearance(data, original_row.item_state, original_row.appearance)
		assert(not appearance.is_empty(), "Fixture equipment projection remains valid: " + str(original_row.item_state))
		return appearance
	army.combat_target_query = func(_identity: int, _bodies: bool) -> Dictionary:
		geometry_calls += 1
		return {}
	var row: Dictionary = army.combat_units[0]
	var cargo: Dictionary = row.cargo
	var bow := _weapon(data, row, "bow_01")
	var crossbow := _weapon(data, row, "crossbow_01")
	var sword := _weapon(data, row, "longsword_01")
	row.item_state.equipped.weapon = bow
	assert(army.ranged_profile(0).get("ammo", "") == "arrow", "The actual equipped bow must produce its arrow profile")
	var snapshot: Dictionary = JSON.parse_string(JSON.stringify(army.capture_combat_state()))
	snapshot.units[0].ranged_cooldown = 2.0
	assert(TerrainArmy.valid_combat_state(snapshot, data))
	for invalid: Variant in [-1.0, 3.01, "0", null, INF, NAN]:
		var corrupt := snapshot.duplicate(true)
		corrupt.units[0].ranged_cooldown = invalid
		assert(not TerrainArmy.valid_combat_state(corrupt, data))
	snapshot.units[0].erase("ranged_cooldown")
	assert(TerrainArmy.valid_combat_state(snapshot, data), "Legacy rows omit the new firing timer without being reinterpreted")
	assert(army.start_unit_attack(0, selected[0] + Vector2i.RIGHT * 6, 9999))
	assert(cargo.arrow == 0 and army.projectiles.is_empty(), "Target selection cannot create a shot or consume ammunition")
	assert(not army.ranged_fire(0, selected[0] + Vector2i.RIGHT * 6, 1), "No original ammunition means no shot")
	assert(cargo.arrow == 0 and army.projectiles.is_empty())
	cargo.arrow = 2 # Explicit fixture stock, never generated by the firing query.
	assert(not army.ranged_fire(0, selected[0] + Vector2i.RIGHT, 1))
	assert(not army.ranged_fire(0, selected[0] + Vector2i.RIGHT * 9, 1))
	var blocked := selected[0] + Vector2i.RIGHT * 3
	data.static_blocked[data.index(blocked)] = 1
	assert(not army.ranged_fire(0, selected[0] + Vector2i.RIGHT * 6, 1))
	data.static_blocked[data.index(blocked)] = 0
	row.item_state.equipped.weapon = sword
	assert(army.ranged_profile(0).is_empty() and not army.ranged_fire(0, selected[0] + Vector2i.RIGHT * 6, 1))
	row.item_state.equipped.weapon = bow
	row.fatigue = 10.0
	row.fatigue_rest = 15.0
	assert(army.activate_exchange_skill(0, "power"))
	var events: Array[float] = []
	army.combat_event.connect(func(seconds: float) -> void: events.append(seconds))
	assert(army.ranged_fire(0, selected[0] + Vector2i.RIGHT * 6, 1))
	assert(is_same(cargo, row.cargo) and cargo.arrow == 1 and cargo.bolt == 2)
	assert(army.projectiles.size() == 1 and row.fatigue == 11.0 and row.fatigue_rest == 0.0)
	var shot: Dictionary = army.projectiles[0]
	assert(shot.shot_id == 1 and shot.shooter_id == army.combat_identity(0) and shot.target_cell == selected[0] + Vector2i.RIGHT * 6)
	assert(shot.mode == "cell" and shot.visual == "arrow" and is_equal_approx(float(shot.total), 0.6))
	assert(shot.shooter.fatigue == 10.0 and shot.shooter.skill == "power" and row.exchange_skill == "")
	assert(row.exchange_skill_cooldown == 8.0 and row.ranged_cooldown == 2.0 and row.exchange_stagger == 0.25)
	assert(float(row.get("exchange_cooldown", 0.0)) == 0.0 and army.exchange_can_receive(0), "Reloading must not grant melee immunity")
	assert(army.combat_frame(0).clip == "attack_bow" and events.has(12.0))
	assert(float(army.contact_sample(0)[1]) == float(TerrainArmy.CombatTimings.events(&"attack_bow").release), "Already released arrows start presentation at the authored release time")
	assert(not army.ranged_fire(0, selected[0] + Vector2i.RIGHT * 6, 2) and cargo.arrow == 1)
	var frozen_shot := shot.duplicate(true)
	row.item_state.equipped.weapon = crossbow
	assert(army.ranged_profile(0).ammo == "bolt" and shot == frozen_shot, "In-flight shot never follows new equipment or a new target")
	army.ranged_apply_hit(0, selected[0] + Vector2i.DOWN, _packet("graze", 1.0, 6.0, 0.2))
	assert(row.hp == 99.0 and row.pose == "hit" and row.ranged_cooldown == 2.0 and row.exchange_stagger == 0.25)
	assert(army.projectiles.size() == 1 and shot == frozen_shot)
	army.prepare_combat(1.0)
	assert(army.exchange_ready(0) and row.ranged_cooldown == 1.0)
	assert(not army.ranged_fire(0, selected[0] + Vector2i.RIGHT * 6, 2) and cargo.bolt == 2, "Finishing a reaction does not shorten the independent firing cadence")
	army.prepare_combat(7.0)
	assert(army.activate_exchange_skill(0, "brace"))
	assert(army.ranged_fire(0, selected[0] + Vector2i.RIGHT * 10, 2))
	assert(cargo.arrow == 1 and cargo.bolt == 1 and army.projectiles.size() == 2)
	assert(row.exchange_skill == "brace" and row.ranged_cooldown == 3.0 and row.exchange_stagger == 0.4)
	assert(army.combat_frame(0).clip == "attack_crossbow")
	army.ranged_apply_hit(0, selected[0] + Vector2i.DOWN, _packet("miss", 0.0, 0.0, 0.0))
	assert(row.exchange_skill == "" and row.exchange_skill_cooldown == 8.0 and row.pose == "attack_crossbow")
	assert(row.hp == 99.0 and row.ranged_cooldown == 3.0 and row.exchange_stagger == 0.4)
	# Other original rows cannot obtain immunity by helping, moving or already
	# recovering. Arrow hits do not push, reset melee cooldown or consume power.
	army.apply_unit_contact(2, {"result": {"hp": 0.0, "stun": 110.0, "guard_break": false}, "shield": false})
	assert(army.start_unit_rescue(1, 2))
	army.ranged_apply_hit(1, selected[1] + Vector2i.UP, _packet("hit", 2.0, 12.0, 0.35))
	assert(army._unit_rescues.is_empty() and army.combat_units[1].hp == 98.0 and army.combat_units[2].ko > 0.0)
	army._wake_unit(2)
	army.prepare_combat(0.4)
	var recovering_row: Dictionary = army.combat_units[2]
	var recovery_age := float(recovering_row.age)
	assert(recovering_row.pose == "get_up" and not army.combat_can_act(2))
	army.ranged_apply_hit(2, selected[2] + Vector2i.LEFT, _packet("graze", 1.0, 6.0, 0.2))
	assert(recovering_row.hp == 99.0 and recovering_row.pose == "get_up" and recovering_row.age == recovery_age,
		"A non-KO arrow cannot replace or restart the original get-up animation")
	assert(not army.combat_can_act(2) and not army.exchange_ready(2))
	army.prepare_combat(1.8)
	var moving_row: Dictionary = army.combat_units[2]
	assert(army._reserve_combat_step(2, selected[2] + Vector2i.UP))
	army.prepare_combat(0.05)
	moving_row.exchange_stagger = 0.7
	moving_row.exchange_cooldown = 0.8
	moving_row.exchange_skill = "power"
	army.ranged_apply_hit(2, selected[2] + Vector2i.LEFT, _packet("graze", 1.0, 6.0, 0.2))
	assert(moving_row.hp == 98.0 and moving_row.exchange_stagger == 0.7 and moving_row.exchange_cooldown == 0.8)
	assert(moving_row.exchange_skill == "power" and army.moving_to[2] == selected[2] + Vector2i.UP)
	assert(army.ranged_defense(2).moving and not army.ranged_defense(2).shield)
	var before_knockout := army.projectiles.duplicate(true)
	army.ranged_apply_hit(0, selected[0] + Vector2i.DOWN, _packet("hit", 2.0, 110.0, 0.35))
	assert(row.ko > 0.0 and row.pose == "down" and army.projectiles == before_knockout)
	var death_ids: Array[int] = []
	army.died.connect(func(identity: int) -> void: death_ids.append(identity))
	army.ranged_apply_hit(0, selected[0] + Vector2i.DOWN, _packet("hit", 100.0, 12.0, 0.35))
	assert(row.hp == 0.0 and row.ko == 0.0 and row.pose == "down" and death_ids == [army.combat_identity(0)])
	assert(army.projectiles == before_knockout and cargo.arrow == 1 and cargo.bolt == 1)
	assert(not army.ranged_fire(0, selected[0] + Vector2i.RIGHT * 6, 3))
	assert(not army.capture_combat_state().has("projectiles"), "Flight events are transient; the Lab's combat/save guard owns active-flight refusal")
	# Ordinary soldier recipes must be explicitly admitted, never substituted by
	# longsword pixels. This remains valid when an authored bow recipe is added.
	army.prepare_combat(1.0)
	var ordinary: Dictionary = army.combat_units[1]
	ordinary.cargo.arrow = 1
	ordinary.item_state.equipped.weapon = _weapon(data, ordinary, "bow_01")
	var supported := army.supports_equipment_recipe(army.equipment_appearance(1))
	var count := army.projectiles.size()
	var fired := army.ranged_fire(1, army.cells[1] + Vector2i.RIGHT * 6, 3)
	assert(fired == supported and ordinary.cargo.arrow == (0 if supported else 1))
	assert(army.projectiles.size() == count + int(supported))
	if not supported:
		assert("圖集" in str(ordinary.status))
	assert(geometry_calls == 0 and TerrainArmy._contact_source == null)
	army.clear()
	assert(army.projectiles.is_empty())
	army.free()
	print("SITE_RANGED_ARMY_PASS: original equipment and ammo alias/conservation, blocked/empty/changed weapon, authored bow/crossbow, frozen released shot, power/brace cooldown, rescue/movement hit guards, original KO/death, no geometry, explicit atlas admission")
	quit(0)
